package utils;

import play.templates.JavaExtensions;

/**
 * Created by Formation on 21/10/2016.
 */
public class CustomExtensions extends JavaExtensions {

    public static String dropDownChamp(String nameObjectSearchFrom,String idForCss)
    {
        String s = "<select name='searchForm."+nameObjectSearchFrom+"' size='1' id='"+idForCss+"'>";
        s+="<option value='Aatrox>Aatrox</option>";
        s+="<option value='Ahri>Ahri</option>";
        s+="<option value='Akali>Akali</option>";
        s+="<option value='Alistar>Alistar</option>";
        s+="<option value='Amumu>Amumu</option>";
        s+="<option value='Anivia>Anivia</option>";
        s+="<option value='Annie>Annie</option>";
        s+="<option value='Ashe>Ashe</option>";
        s+="<option value='Aurelion Sol>Aurelion Sol</option>";
        s+="<option value='Azir>Azir</option>";
        s+="<option value='Bard>Bard</option>";
        s+="<option value='Blitzcrank>Blitzcrank</option>";
        s+="<option value='Brand>Brand</option>";
        s+="<option value='Braum>Braum</option>";
        s+="<option value='Caitlyn>Caitlyn</option>";
        s+="<option value='Cassiopeia>Cassiopeia</option>";
        s+="<option value='ChoGath>ChoGath</option>";
        s+="<option value='Corki>Corki</option>";
        s+="<option value='Darius>Darius</option>";
        s+="<option value='Diana>Diana</option>";
        s+="<option value='Draven>Draven</option>";
        s+="<option value='Ekko>Ekko</option>";
        s+="<option value='Elise>Elise</option>";
        s+="<option value='Evelynn>Evelynn</option>";
        s+="<option value='Ezreal>Ezreal</option>";
        s+="<option value='Fiddlestick>Fiddlestick</option>";
        s+="<option value='Fiora>Fiora</option>";
        s+="<option value='Fizz>Fizz</option>";
        s+="<option value='Galio>Galio</option>";
        s+="<option value='Gangplank>Gangplank</option>";
        s+="<option value='Garen>Garen</option>";
        s+="<option value='Gnar>Gnar</option>";
        s+="<option value='Gragas>Gragas</option>";
        s+="<option value='Graves>Graves</option>";
        s+="<option value='Hecarim>Hecarim</option>";
        s+="<option value='Heimerdinger>Heimerdinger</option>";
        s+="<option value='Illaoi>Illaoi</option>";
        s+="<option value='Irelia>Irelia</option>";
        s+="<option value='Janna>Janna</option>";
        s+="<option value='Jarvan IV>Jarvan IV</option>";
        s+="<option value='Jax>Jax</option>";
        s+="<option value='Jayce>Jayce</option>";
        s+="<option value='Jhin>Jhin</option>";
        s+="<option value='Jinx>Jinx</option>";
        s+="<option value='Kalista>Kalista</option>";
        s+="<option value='Karma>Karma</option>";
        s+="<option value='Karthus>Karthus</option>";
        s+="<option value='Kassadin>Kassadin</option>";
        s+="<option value='Katarina>Katarina</option>";
        s+="<option value='Kayle>Kayle</option>";
        s+="<option value='Kennen>Kennen</option>";
        s+="<option value='Kha'Zix>Kha'Zix</option>";
        s+="<option value='Kindred>Kindred</option>";
        s+="<option value='Kled>Kled</option>";
        s+="<option value='Kogmaw>Kogmaw</option>";
        s+="<option value='Leblanc>Leblanc</option>";
        s+="<option value='Leesin>Leesin</option>";
        s+="<option value='Leona>Leona</option>";
        s+="<option value='Lissandra>Lissandra</option>";
        s+="<option value='Lucian>Lucian</option>";
        s+="<option value='Lulu>Lulu</option>";
        s+="<option value='Lux>Lux</option>";
        s+="<option value='Maitre Yi>Maitre Yi</option>";
        s+="<option value='Malphite>Malphite</option>";
        s+="<option value='Malzahar>Malzahar</option>";
        s+="<option value='Maokai>Maokai</option>";
        s+="<option value='Miss Fortune>Miss Fortune</option>";
        s+="<option value='Mordekaiser>Mordekaiser</option>";
        s+="<option value='Morgana>Morgana</option>";
        s+="<option value='Mundo>Mundo</option>";
        s+="<option value='Nami>Nami</option>";
        s+="<option value='Nasus>Nasus</option>";
        s+="<option value='Nautilus>Nautilus</option>";
        s+="<option value='Nidalee>Nidalee</option>";
        s+="<option value='Nocturne>Nocturne</option>";
        s+="<option value='Nunu>Nunu</option>";
        s+="<option value='Olaf>Olaf</option>";
        s+="<option value='Orianna>Orianna</option>";
        s+="<option value='Pantheon>Pantheon</option>";
        s+="<option value='Poppy>Poppy</option>";
        s+="<option value='Quinn>Quinn</option>";
        s+="<option value='Rammus>Rammus</option>";
        s+="<option value='Reksai>Reksai</option>";
        s+="<option value='Renekton>Renekton</option>";
        s+="<option value='Rengar>Rengar</option>";
        s+="<option value='Riven>Riven</option>";
        s+="<option value='Rumble>Rumble</option>";
        s+="<option value='Ryze>Ryze</option>";
        s+="<option value='Sejuani>Sejuani</option>";
        s+="<option value='Shaco>Shaco</option>";
        s+="<option value='Shen>Shen</option>";
        s+="<option value='Shyvana>Shyvana</option>";
        s+="<option value='Singed>Singed</option>";
        s+="<option value='Sion>Sion</option>";
        s+="<option value='Sivir>Sivir</option>";
        s+="<option value='Skarner>Skarner</option>";
        s+="<option value='Sona>Sona</option>";
        s+="<option value='Soraka>Soraka</option>";
        s+="<option value='Swain>Swain</option>";
        s+="<option value='Syndra>Syndra</option>";
        s+="<option value='Tahm Kench>Tahm Kench</option>";
        s+="<option value='Taliyah>Taliyah</option>";
        s+="<option value='Talon>Talon</option>";
        s+="<option value='Taric>Taric</option>";
        s+="<option value='Teemo>Teemo</option>";
        s+="<option value='Thresh>Thresh</option>";
        s+="<option value='Tristana>Tristana</option>";
        s+="<option value='Trundle>Trundle</option>";
        s+="<option value='Tryndamere>Tryndamere</option>";
        s+="<option value='Twisted Fate>Twisted Fate</option>";
        s+="<option value='Twitch>Twitch</option>";
        s+="<option value='Udyr>Udyr</option>";
        s+="<option value='Urgot>Urgot</option>";
        s+="<option value='Varus>Varus</option>";
        s+="<option value='Vayne>Vayne</option>";
        s+="<option value='Veigar>Veigar</option>";
        s+="<option value='Velkoz>Velkoz</option>";
        s+="<option value='Vi>Vi</option>";
        s+="<option value='Viktor>Viktor</option>";
        s+="<option value='Vladimir>Vladimir</option>";
        s+="<option value='Volibear>Volibear</option>";
        s+="<option value='Warwick>Warwick</option>";
        s+="<option value='Wukong>Wukong</option>";
        s+="<option value='Xerath>Xerath</option>";
        s+="<option value='Xin Zhao>Xin Zhao</option>";
        s+="<option value='Yasuo>Yasuo</option>";
        s+="<option value='Yorick>Yorick</option>";
        s+="<option value='Zac>Zac</option>";
        s+="<option value='Zed>Zed</option>";
        s+="<option value='Ziggs>Ziggs</option>";
        s+="<option value='Zilean>Zilean</option>";
        s+="<option value='Zyra>Zyra</option>";
        s +="</select>";
        return s;
    }
}
